### ISSUE TITLE
pip install perceval 0.5.0 keeps version on 0.4.0

### ISSUE THREAD

**Issue by robinmuilwijk** [grimoirelab/perceval#110]
Hi,

A question. I already asked on Twitter yesterday (https://twitter.com/jgbarah/status/821836366656995333) I had some problems updating perceval through pip. I was trying to install/update to the latest release 0.5.0. but instead it only updated to 0.4.0.

I did this with: $ sudo pip3 install perceval --upgrade

You fixed the pip package. After that I ran the upgrade again, and the terminal output did report back perceval 0.4.0. was being removed, and perceval 0.5.0. being installed.

However, if I run: $ pip3 show perceval, it still shows 0.4.0. I also checked the file _version.py and this also says 0.4.0. 

Did I do something wrong? Because the update to 0.5.0 failed yesterday (because pip package was not in place yet) I manually fixed issue #92 with the utc date in backend.py. This should not be a problem right?

Hoping you have an answer to this, so I can update to 0.5.0.

Thanks, Robin

**Comment by sduenas** [comment]
@robinmuilwijk, I didn't find any problem installing 0.4.0 and upgrading to 0.5.0.

Maybe you have several versions of Perceval installed on the same system. You can check if the version that your system is using by default matches with the one installed by pip. First, on a terminal run:

```
$ which perceval
```

It should return the path to the `perceval` command.

You can also check which packages Python is using. You have to open a python interpreter and type some statements.
```
$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import perceval
>>> perceval.__path__
['/home/sduenas/.local/lib/python3.5/site-packages/perceval-0.5.0-py3.5.egg/perceval']
```

This path should match with the place where pip installed perceval package. My path points to another place because I install perceval from sources.

Would you mind to check it?

By the way, these are the steps that I followed to test that upgrading from 0.4.0 to 0.5.0 works perfect for me. I used a virtual environment to test it. Maybe you can follow the same steps and check whether this works for you.

* Create virtual environment
```
$ python3 -m venv /tmp/venv_perceval
$ source /tmp/venv_perceval/bin/activate
```

* Install 0.4.0
```
(venv_perceval) :~$ pip3 install perceval==0.4.0
Collecting perceval==0.4.0
  Using cached perceval-0.4.0-py3-none-any.whl
Collecting python-dateutil>=2.0.0 (from perceval==0.4.0)
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting requests>=2.7.0 (from perceval==0.4.0)
  Using cached requests-2.12.5-py2.py3-none-any.whl
Collecting beautifulsoup4>=4.3.2 (from perceval==0.4.0)
  Using cached beautifulsoup4-4.5.3-py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2.0.0->perceval==0.4.0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, requests, beautifulsoup4, perceval
Successfully installed beautifulsoup4-4.5.3 perceval-0.4.0 python-dateutil-2.6.0 requests-2.12.5 six-1.10.0

(venv_perceval) :~$ pip3 show perceval
---
Metadata-Version: 2.0
Name: perceval
Version: 0.4.0
[...]
```

* Upgrade perceval
```
(venv_perceval) :~$ pip3 install perceval --upgrade
Collecting perceval
  Using cached perceval-0.5.0-py3-none-any.whl
[...]
Installing collected packages: feedparser, perceval
  Running setup.py install for feedparser ... done
  Found existing installation: perceval 0.4.0
    Uninstalling perceval-0.4.0:
      Successfully uninstalled perceval-0.4.0
Successfully installed feedparser-5.2.1 perceval-0.5.0

(venv_perceval) :~$ pip3 show perceval
---
Metadata-Version: 2.0
Name: perceval
Version: 0.5.0
[...]

(venv_perceval) :~$ perceval -v
perceval 0.5.0

(venv_perceval) :~$ deactivate
```

**Comment by robinmuilwijk** [comment]
Thanks for looking into this, and the feedback. I will test it as soon as possible. I followed the gitbook by Jesus for the installation. As far as I know, I should just have one instance of perceval, in a virtual python env. I'll let you know once I have tested and ran all the commands you suggested.

**Comment by jgbarah** [comment]
Hi, @robinmuilwijk, if you're installing with

```
$ sudo pip3 install perceval --upgrade
```

maybe you're not using the virtualenv (at least for that). In short, when you're "sudoing", you're executing as root, not as you. Instead, I would update perceval as:

```
[activate virtual environment, probably by running source XXX/perceval/bin/activate]
(perceval) $ perceval --version
(perceval) $ pip3 install perceval --upgrade
(perceval) $ perceval --version
```

The first `perceval --version` should show `0.4.0`(assuming you hadn't upgraded it yet), and in any case, the second one should show `0.5.0`.

Would you mind trying that, please, and reporting the result, if different from above?

**Comment by robinmuilwijk** [comment]
Thank you! That did the trick indeed. Not sudoing, but simply using: $ pip3 install perceval --upgrade

If I now run: $ perceval --version, I get 0.5.0 as output.

Thanks so much for the help. On with the quest to complete the dashboard.

**Comment by jgbarah** [comment]
Great! I'm closing this, then.
