### ISSUE TITLE
Gerrit backend must use 'number' instead 'id' as unique identifier

### ISSUE THREAD

**Issue by acs-test** [grimoirelab/perceval#116]
The id is the Change-Id, the identifier of the change, but the same change could be used in different reviews.
For example, all this reviews have the same id but different number:

https://gerrit.opnfv.org/gerrit/22009
https://gerrit.opnfv.org/gerrit/22007
https://gerrit.opnfv.org/gerrit/21997

**Comment by sduenas** [comment]
:+1:
