### ISSUE TITLE
[gerrit] Error retrieving version every first time

### ISSUE THREAD

**Issue by albertinisg** [grimoirelab/perceval#132]
I've been checking that every first time we try to retrieve gerrit information using ssh, perceval will fail. Having a look into it with @sduenas, the following approach http://askubuntu.com/questions/87449/how-to-disable-strict-host-key-checking-in-ssh can avoid this check.

We could implement this as a parameter in perceval, so the user can disable the `host key checking` or not.

**Comment by acs** [comment]
Implemented in:
https://github.com/grimoirelab/perceval/pull/134
