### ISSUE TITLE
Collect GitHub reactions

### ISSUE THREAD

**Issue by sduenas** [grimoirelab/perceval#155]
Issues should include reactions data. 

https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments
https://developer.github.com/v3/reactions/

Take into account due to it is still in preview, the API may change.

https://developer.github.com/changes/2016-05-12-reactions-api-preview/

**Comment by hmitsch** [comment]
This is awesome! Can somebody help me understand when this will become available to Mozilla's Community Analytics instance? When will we be able to see Github reactions in our data?

**Comment by jsmanrique** [comment]
It's an on-going process @hmitsch. 

Once Perceval is able to gather the data to include them as part of the raw data from github, GrimoireELK should be able to handle them to include relevant information in the enriched index ([issue 98 in GrimoireELK repo](https://github.com/grimoirelab/GrimoireELK/issues/98)). 

Once the data are in the enriched index, the panels team would need to update current github related panels.

**Comment by hmitsch** [comment]
Very helpful. Thank you @jsmanrique!
