### ISSUE TITLE
Add an option to GitHub backend to avoid getting comments and reactions

### ISSUE THREAD

**Issue by acs** [grimoirelab/perceval#162]
Now that the github backed collects comments and reactions in the issues, the rate limit needed to analyze a github repository has increased significantly.

For example, a small repository like the perceval one  with <100 issues (https://github.com/grimoirelab/perceval/issues)  now needs around 1500 queries to the GitHub API. So the analysis of large repositories could be pretty slow.

A possible solution is to add a new option to the github backend to avoid getting comments if they are not needed.

**Comment by acs** [comment]
Great @valeriocos to reduce the number of queries to the GitHub API! This is critical in large repositories.

**Comment by valeriocos** [comment]
Instead of adding an option, we can see how to optimize the number of requests to the GitHub API (as we did with reactions in pull request #163)

**Comment by sduenas** [comment]
The rationale behind closing this ticket is we don't want to have first class items. All items of the same category (in this case, GitHub issues) must contain the same information.
There are better ways to handle the calls to the API. See #163.

We will continue working on this issue in #168
