### ISSUE TITLE
ImportError: No module named 'bs4'

### ISSUE THREAD

**Issue by brylie** [grimoirelab/perceval#26]
On a new Perceval installaiton, I get the following error when running the script:

```py
Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 30, in <module>
    from perceval.backends import PERCEVAL_CMDS
  File "/usr/local/lib/python3.4/dist-packages/perceval/backends/__init__.py", line 23, in <module>
    from .bugzilla import Bugzilla, BugzillaCommand
  File "/usr/local/lib/python3.4/dist-packages/perceval/backends/bugzilla.py", line 31, in <module>
    import bs4
ImportError: No module named 'bs4'

```

It would be helpful to document the module requirements, so that users can be sure everything will work as expected.

# Reference
* [Installing Beautiful Soup](http://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-beautiful-soup)
* [Installing Python 3 pip on Ubuntu](http://askubuntu.com/a/506295/81084)

**Comment by sduenas** [comment]
The list of required modules is available in [requirements section](https://github.com/grimoirelab/perceval#requirements) of README.md and in [requirements.txt](https://github.com/grimoirelab/perceval/blob/master/requirements.txt).

The dependency with Beautiful Soup is there from the beginning of the project, I think :-)

**Comment by brylie** [comment]
Cool, I overlooked the requirements, and had to figure out how specifically to install them.

**Comment by sduenas** [comment]
Ok, I think we need to improve the documentation about dependencies installation.

I close this issue. Feel free to open a new one if you find new problems. Thanks.

**Comment by brylie** [comment]
Thanks @sduenas

**Comment by gpoo** [comment]
@sduenas May be add an instruction about how to use `pip` to install the dependencies using the `requirements.txt` file.

```
$ pip install -r requirements
```

Btw, the Readme states minimum versions for each module, but these versions are not in the `requirements.txt` file.

**Comment by sduenas** [comment]
@gpoo I solved the problems that you mentioned here 7dac86f

**Comment by gpoo** [comment]
There is a typo, also because I made it in my comment. It should be `requirements.txt` instead of `requirements`.

**Comment by RaviFefar** [comment]
Activate the **virtualenv**, and then install **BeautifulSoup4**:

`$ pip install BeautifulSoup4`

When you installed **bs4** with **easy_install**, you installed it system-wide. So your system python can import it, but not your **virtualenv** python.

**Comment by RaviFefar** [comment]
> On a new Perceval installaiton, I get the following error when running the script:
> 
> ```python
> Traceback (most recent call last):
>   File "/usr/local/bin/perceval", line 30, in <module>
>     from perceval.backends import PERCEVAL_CMDS
>   File "/usr/local/lib/python3.4/dist-packages/perceval/backends/__init__.py", line 23, in <module>
>     from .bugzilla import Bugzilla, BugzillaCommand
>   File "/usr/local/lib/python3.4/dist-packages/perceval/backends/bugzilla.py", line 31, in <module>
>     import bs4
> ImportError: No module named 'bs4'
> ```
> 
> It would be helpful to document the module requirements, so that users can be sure everything will work as expected.
> 
> # Reference
> * [Installing Beautiful Soup](http://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-beautiful-soup)
> * [Installing Python 3 pip on Ubuntu](http://askubuntu.com/a/506295/81084)

Activate the virtualenv, and then install BeautifulSoup4:

$ pip install BeautifulSoup4

When you installed bs4 with easy_install, you installed it system-wide. So your system python can import it, but not your virtualenv python.
