### ISSUE TITLE
setup.py having UTF-8 characters causing trouble in readthedocs

### ISSUE THREAD

**Issue by jgbarah** [grimoirelab/perceval#32]
I see readthedocs is failing when processing the setup.py file:

```
 python setup.py install --force
Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    fd.read(), re.MULTILINE).group(1)
  File "/home/docs/checkouts/readthedocs.org/user_builds/perceval/envs/stable/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 794: ordinal not in range(128)
```

The problem seems to be:

* For some reason, the default codec for readthedocs seems to be ascii instead of utf8
* There is a utf8 char in the perceval/_version.py file: 

```
#     Santiago Dueñas <sduenas@bitergia.com>
```

That seems to make the parsing fail when reading the file, if the default encoding is ASCII, which seems to be the case in readthedocs.

If you're having utf8 by default, you can still reproduce the error by using LC_ALL=C:

```
(perceval)jgb@expisito:~/src/grimoirelab/perceval$ LC_ALL=C python setup.py install --force
Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    fd.read(), re.MULTILINE).group(1)
  File "/home/jgb/venvs/perceval/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 794: ordinal not in range(128)
``` 

I see two fixes:

* Removing the header from perceval/_version.py. In the end, that file probably doesn't need a header... That would avoid the bug by removing the utf8 char.

* Teaching setup.py to use utf when reading perceval/_version.py. For example:

```
with open('perceval/_version.py', 'r', encoding="utf-8") as fd:
    version = re.search(r'^__version__\s*=\s*[\'"]([^\'"]*)[\'"]',
                        fd.read(), re.MULTILINE).group(1)
```

I guess any of these would solve the problem. Please, fix it so that we can have updated readthedocs documentation, and in addition, the setup.py works in non-utf8 environments.

**Comment by sduenas** [comment]
@jgbarah thanks for sharing it. I will remove the header from the file but I will also open the file as `utf-8` to avoid any future problems.
