### ISSUE TITLE
[mbox] Error when parsing a specific date

### ISSUE THREAD

**Issue by dicortazar** [grimoirelab/perceval#57]
I found the following error when parsing a mailing list file in mbox format.

```
Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 176, in <module>
    main()
  File "/usr/local/bin/perceval", line 97, in main
    cmd.run()
  File "/usr/local/lib/python3.4/dist-packages/perceval/backends/mbox.py", line 330, in run
    raise RuntimeError(str(e))
RuntimeError: Thu, 14 Aug 2008 02:07:59 +0200 CEST is not a valid date
~/$ perceval mbox --no-cache --origin=evince mboxes ./gmane.comp.emulators.qemu
```

**Comment by sduenas** [comment]
This error is raised by `str_to_datetime` function from `perceval.utils` module.

The parser that we use to convert these strings to datetime objects fails when it finds something after the timezone numeric data. In this case with `CEST` substring. We had similar problem with parentheses (see 8735246751ddefd007d4dd647d3cbe7aeac6919e)

**Comment by sduenas** [comment]
Fixed.
