### ISSUE TITLE
FilePath not stored in some cases such as merges

### ISSUE THREAD

**Issue by dicortazar** [grimoirelab/perceval#63]
There are commits like merges whose log contains information about the filepath but this filepath is not displayed by Perceval.

This commit: https://kernel.googlesource.com/pub/scm/linux/kernel/git/davem/net-next/+/8cbdd85bda499d028b8f128191f392d701e8e41d . In this commits Perceval only stores the number of added and removed lines, but not the filepath.

[commit_8cbdd85bda499d028b8f128191f392d701e8e41d.txt](https://github.com/grimoirelab/perceval/files/482081/commit_8cbdd85bda499d028b8f128191f392d701e8e41d.txt)

In order to provide some numbers, if the Linux kernel is analyzed at the level of changes in the files, 9 M out of 11 M of them do not contain this filepath. As those are mainly merges, that information is still there spread in other commits, so it's not a big deal :).

**Comment by sduenas** [comment]
Fixed.
