### ISSUE TITLE
[phabricator] Maniphest items don't include tags

### ISSUE THREAD

**Issue by acs** [grimoirelab/perceval#64]
In the tasks retrieved by the current phabricator backend for maniphest items (tasks), the tags linked to the task are not included.

**Comment by sduenas** [comment]
What do you mean exactly? In Maniphest, tasks can have tokens, flags and projects (aka tags). None of these are retrieved. Which one do you want to be retrieved?

**Comment by acs** [comment]
@sduenas changed flags for tags in the ticket subject. Tags is the missing piece to know in which tags/projects are tasks.
