### ISSUE TITLE
python3-setuptools requirement seems to be missed

### ISSUE THREAD

**Issue by jsmanrique** [grimoirelab/perceval#71]
```
$ sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    from setuptools import setup
ImportError: No module named 'setuptools'
```

I've installed it with `apt` and after that, Perceval installs perfectly

**Comment by shongoku** [comment]
Hello jsmanrique,

Have you installed the setuptools before?

sudo apt-get install python3-setuptools

**Comment by jsmanrique** [comment]
No, I installed them after the `ImportError`.

**Comment by shongoku** [comment]
And after does work it?

**Comment by jsmanrique** [comment]
Yes, that's why I've opened the bug. You need to have python3-setuptools installed before installing perceval, and I don't see it in the 'requirements'

**Comment by shongoku** [comment]
I sent a new pull request to add the setuptools framework in requirement.txt file. I hope this change fix the problem
