### ISSUE TITLE
Parsing webkit-dev pipermail, all items before Oct. 2007 collapse in one month

### ISSUE THREAD

**Issue by jsmanrique** [grimoirelab/perceval#72]
After running:
```
python3 ./p2o.py --enrich --index mls_webkit_dev -e http://localhost:9200 --no_inc --debug pipermail https://lists.webkit.org/pipermail/webkit-dev/
```

I get posts older than Oct. 9th 2007 set to `grimoire_creation_date` as Oct. 9th, 2007

![kibana-webkit-dev-mls](https://cloud.githubusercontent.com/assets/1178305/19043819/0986fabc-8992-11e6-8819-efa705ad1f67.jpg)

**Comment by sduenas** [comment]
This is not a bug on perceval. Please open it in GrimoireELK.
