### ISSUE TITLE
failed Tests

### ISSUE THREAD

**Issue by shongoku** [grimoirelab/perceval#77]
I've checked the tests and often a lot of then fail. Is it normal?

**Comment by acs** [comment]
Test are run by travis everytime a commit is done or a PR is requested. Right now tests are ok as you can see from:

https://travis-ci.org/grimoirelab/perceval

How are you running the tests?

**Comment by shongoku** [comment]
I run the run_tests.py 
For example:
josemi@josemi-VirtualBox:~/perceval/tests$ python3 ./run_tests.py 
EEE.....EE........EEEEEEEEEEEEEEEEE

**Comment by acs** [comment]
@shongoku try to execute a single backend tests to get in the output the error. For example:

    ~/devel/perceval/tests $ python3 ./test_remo2.py

I am pretty sure that your problem is that you need to install httpretty for testing.

**Comment by shongoku** [comment]
Yes, it is. A problem is that I must install httppretty. If it is necessary the httppretty tool, don't we put in requirements.txt file?
Other problem is:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 321, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "/usr/lib/python3.5/http/client.py", line 208, in parse_headers
    raise LineTooLong("header line")
http.client.LineTooLong: got more than 65536 bytes when reading header line

**Comment by acs** [comment]
@shongoku how did you get the last error?

**Comment by shongoku** [comment]
System: Ubuntu desktop 16.04.1 64 bits under VirtualBox

I got it:

josemi@josemi-VirtualBox:~/perceval/tests$ python3 run_tests.py 
.........................................................................E.EE.E.................................................................................E..E.......................................................E..E..E...E.E
Stderr:
WARNING:perceval.backends.mediawiki:Test mode active; MAX_RECENT_DAYS limit ignored
......E........E.E.......E..............................EE.E..E...............................................................................
======================================================================
ERROR: test_fetch (test_discourse.TestDiscourseBackend)
Test whether a list of topics is returned
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 321, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "/usr/lib/python3.5/http/client.py", line 208, in parse_headers
    raise LineTooLong("header line")
http.client.LineTooLong: got more than 65536 bytes when reading header line

During handling of the above exception, another exception occurred:

**Comment by maelick** [comment]
I have the exact same errors on Debian Jessie.

**Comment by sduenas** [comment]
@maelick are you using Python 3.5 too?

**Comment by maelick** [comment]
No 3.4.2

**Comment by sduenas** [comment]
@maelick It's weird. Tests on Travis are using the same version of Python that you're using.

Are all the errors `http.client.LineTooLong` exceptions? Do you mind to paste her the full tests output?

**Comment by maelick** [comment]
@sduenas It's quite long so I put it in the following gist: https://gist.github.com/maelick/81619ccbba64fc54729300c4d9f74b01

**Comment by sduenas** [comment]
I still don't know what is going on. It seems something related to `httpretty` library but I'm not sure.

@maelick, @shongoku, which version of `httpretty` are you using? Are you running Perceval in a virtual machine?

**Comment by maelick** [comment]
@sduenas 0.8.14, the latest from PyPI. No VM for me.

**Comment by sduenas** [comment]
I found the problem. Running the tests with httpretty 0.8.14 makes them fail, while using version 0.8.6 (the one I have on my computer and on Travis) produces a successful result.

**Comment by sduenas** [comment]
I traced the bug and I noticed that it is fixed on master (see https://github.com/gabrielfalcao/HTTPretty/commit/7935ab4bd3288129136fbc890ba5e55a8f34609f). A new release will fix this error.
