### ISSUE TITLE
remo2 backend is not installed

### ISSUE THREAD

**Issue by acs** [grimoirelab/perceval#81]
When executing:

`(acs@dellx) (master $% u=) ~/devel/perceval $ sudo python3 setup.py install`

remo2 backend is not installed

```
(acs@dellx) (master $% u=) ~/devel/perceval $ perceval | grep remo
    remo             Fetch events and people from a ReMo site

```

Probably is related with the fact that remo and remo2 both have the class 

`class ReMo(Backend):`

and the automatic detection of backend classes does not support it.

**Comment by acs** [comment]
Strange:

perceval remo
perceval remo2

both of them works .... so I need to research more about this ticket. Maybe it is just a bug showing the list of perceval backends available.

**Comment by sduenas** [comment]
The list of backends that `help` option shows is not generate on the fly. It is hardcoded.

**Comment by acs** [comment]
@sduenas  fixed in: https://github.com/grimoirelab/perceval/pull/82
