### ISSUE TITLE
[jira] The Jira backend starts from the newest issues instead of starting from the oldest ones

### ISSUE THREAD

**Issue by dicortazar** [grimoirelab/perceval#89]
Hi!

I've been playing with the Jira backend of Perceval. I noticed that this starts from the newest issues instead of starting to retrieve information from the oldest ones.

As the incremental support relies on the last date, this means that there's not an actual incremental support for Jira if the connection drops (but this may work if everything's working fine).

How to reproduce the error: 

``
perceval -g jira 'https://issues.apache.org/jira' --project PIG
``

Thanks!

**Comment by sduenas** [comment]
I've checked that the items are returned without an specific order. For instance, after running that command, I got this sequence:
```
1477630191.0
1477629825.0
1477377597.0
1477377630.0
1477583593.0
```
