### ISSUE TITLE
JIRA support

### ISSUE THREAD

**Issue by lluismf** [grimoirelab/perceval#9]
Hi !

I'm a volunteer of OpenMRS, we need to gather bug info from JIRA (among other sources). Is there anything planned? I could give a hand.

Cheers

**Comment by sduenas** [comment]
Hi,

our plan is to include it as soon as possible. In the meantime, you can try with [Bicho](https://github.com/MetricsGrimoire/Bicho) and the set of tools of [MetricsGrimoire](https://github.com/MetricsGrimoire). And of course, any help is welcome.

**Comment by lluismf** [comment]
The plan is to use the new stack (Elastic search + Kibana) not the old one. Do you have an issue tracker? I'm a Python newbie and I would like to start with some intro tickets (if possible).

**Comment by sduenas** [comment]
I see. We use GitHub as an issue tracker but I'm afraid there aren't bugs reported yet.

If you want to start developing a backend for JIRA, you have some examples on `perceval.backends` package. We usually define an API client, to make request to a server (in your case to the JIRA repository) and then a `Backend` class that uses the client to fetch, parse and return the requested data.

The [Bicho's JIRA backend](https://github.com/MetricsGrimoire/Bicho/blob/master/bicho/backends/jira.py) is a little messy but the [JiraBackend](https://github.com/MetricsGrimoire/Bicho/blob/master/bicho/backends/jira.py#L840) class is the only thing you need to use as a reference to know how to do some queries to a JIRA server.

**Comment by acs** [comment]
@lluismf we have also a sample backend that could be useful as reference when creating a new one:

https://github.com/acs/perceval/blob/hello/perceval/backends/hello.py

**Comment by lluismf** [comment]
ok I will take a look at the code. The idea is to use the REST api instead of web scraping, right?

**Comment by acs** [comment]
Yes, avoid web scrapping unless it is the only way to get valuable information.

**Comment by albertinisg** [comment]
Hi @lluismf !

We've been working on the implementation of the JIRA backend. 

An initial version  #14 is now under review process. 

There's still work to do (like testing) but with this initial implementation you will be able already to retrieve issues and (almost) all the information related to each issue, including its history and transitions among others. The only mandatory field is the endpoint URL of your JIRA to fetch all the issues. 

Also, you can filter them by project using the param `--project` and do authenticated requests using `--backend-user` and `--backend-password`.

To get all the available options run:
```
perceval jira --help
```

Best!

**Comment by lluismf** [comment]
Hi Alberto

ok I'll take a look and test it with this repository:
https://issues.openmrs.org
I've been playing around with the Java client API because I don't know
Python.

Cheers



2016-02-24 11:32 GMT+01:00 Alberto Martín <notifications@github.com>:

**Comment by albertinisg** [comment]
Cool. Take note that authenticated requests returns richer information :)

**Comment by sduenas** [comment]
Fixed. Jira backend has been merged into `master` branch.
