### ISSUE TITLE
The items perceval timestamp should be in UTC

### ISSUE THREAD

**Issue by acs** [grimoirelab/perceval#92]
https://github.com/grimoirelab/perceval/blob/master/perceval/backend.py#L194

I think we need to change:

                    'timestamp' : dt.now().timestamp(),

with:

                    'timestamp' : dt.now().utctimestamp(),

What do you think @sduenas ?

**Comment by sduenas** [comment]
I agree but the call should be `dt.utcnow().timestamp()` not `dt.now().utctimestamp()` :-)
