### ISSUE TITLE
Undeclared dependency on install

### ISSUE THREAD

**Issue by iganchevup8** [grimoirelab/perceval#94]
While installing perceval, some dependencies were installed (requests, beautifulsoup, etc).

After installing and launching the software I had the following issue: 
`Import error: no module named configparser`

After installing python-configparser the program works smoothly. Is there a need python-configparser to be added as a dependency during installation?

**Comment by sduenas** [comment]
`configparser` is part of the [Python standard library](https://docs.python.org/3/library/configparser.html) so you shouldn't need to install it. In CPython, you can find the module [here](https://github.com/python/cpython/blob/master/Lib/configparser.py).

Are you running Python 3.4 or greater? This module was first included in Python 3.2, I think. Before it was called `ConfigParser` (at least in Python 2.7).

**Comment by iganchevup8** [comment]
In fact I didn't pay attention that I was using python 2.7. With python 3.5 everything runs smoothly. Sorry about that.
