### ISSUE TITLE
Structure of table extracted in Git

### ISSUE THREAD

**Issue by MishiR** [grimoirelab/perceval#97]
I have used git to retrieve commit data. Are there any documents that explain the structure of the table. What information is extracted in "Action" field is recording?

**Comment by sduenas** [comment]
There aren't tables on Perceval. Data is printed out to the standard input. If you want to know which information is fetched you can either run Perceval and check the output or visit the parser used on Git.
https://github.com/grimoirelab/perceval/blob/master/perceval/backends/core/git.py#L294
